### PR TITLE
Fixed paths and line endings

### PR DESCRIPTION
**Pull request by audriddax**
Running the image on Centos 8, maps were failing to complete because the paths for their various assets (such as the vmt files) were uppercase and did not match the filesystem.

Long term I'd like to see if I can get the maps/models/textures/etc. updated upstream to use the proper pathing. Not sure how long that will take, or if it's possible, but for now this fix updates the filesystem to match the assets.

Additionally, some of the .txt configuration files were using windows line-endings, not unix style. this was causing issues trying to load them, so I ran dos2unix to fix that.

### CODE REVIEW

**Comment by dudleycodes** [comment]
@audriddax Thanks for this PR and these commits!

Do you have any example of the error messages you were receiving? I'd like to add them to the self-test script (https://github.com/LacledesLAN/gamesvr-gesource/blob/master/linux/ll-tests/gamesvr-gesource.sh) to ensure they can't ever go unnoticed should they get reintroduced at anytime in the future.

**Comment by audriddax** [comment]
@dudleycodes yup!

Here are examples of the pathing issues:
```Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/DOORFRAME.vmt)
Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/ROLLUPDOOR01.vmt)
Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/ROLLUPDOOR01.vmt)
Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/ROLLUPDOOR01.vmt)
Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/ROLLUPDOOR01.vmt)
Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/ROLLUPDOOR01.vmt)
Failed to load $include VMT file (materials/GOLDENEYE/RUNWAY/ROLLUPDOOR01.vmt)
```

Here are examples of the line-ending issues:
```Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
Invalid scenario '' included in gameplay cycle file. Ignored.
```
The line endings took a bit to track down because the full logs didn't really give more info that above, but I finally tracked it to gameplaycycle.txt, which has 12 lines, which tracks the errors above. 11 of the 12 lines end in a new line, but the final line, YOLT, doesn't have a newline, it's EOF.

**Comment by audriddax** [comment]
There are other issues I'd like to get resolved. Some I'm pretty sure are upstream:
```SOLID_VPHYSICS static prop with no vphysics model! (models/props/bunker/ventductset01_hangar.mdl)
ConVarRef room_type doesn't point to an existing ConVar```

But I'm also getting these:
```/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/gameserver.cpp (682) : Assertion Failed: m_CMInterface.GetLogonState() == k_ELogonStateNotLoggedOn
Could not establish connection to Steam servers.```
Not sure the first one matters, the second resolves itself in 5 minutes, I think it's some weird DNS issue. It used to be more inconsistent when VAC would init (I'm running a public server), but when I finally was able to sniff traffic enough to catch the cm0.steampowered.com DNS request, and passed it in via the additional hosts parameter, I get a consistent 5 minutes before connections to steam succeed. I've got a friend who's way more knowledgeable on the networking side taking a look at wireshark logs to try and track what's going on, if it's something that can be resolved consistently with an update here, I'll post another PR.

**Comment by dudleycodes** [comment]
@audriddax thanks for the example error messages; they've been added to the self-test scripts!

Unfortunately I don't have a clue as to what could be causing the others; are you running the server via Docker? Are you use `--net=host` for the network linking or something else?

**Comment by audriddax** [comment]
@dudleycodes I was using --net=host for convenience, but I've been playing around with doing explicit port forwarding to the container so that I can run multiple servers. What's the best way to document things like this with you guys?

Also, do you mind if I open issues for things like that convar error above? I'm not expecting you to solve these, I'm looking into them myself, I just want a way to track this. If it's a solution that can be implemented in your repo (and makes sense), I'd like to do that.

**Comment by dudleycodes** [comment]
@audriddax 

> What's the best way to document things like this with you guys?

Whenever running a Docker-ized game server knowing the port mapping (e.g. `--net=host`, `-p 20015/tcp -p 27015/udp`, etc) as well as the Docker engine (Docker on Linux ###, Docker Desktop for Windows ###, Docker Desktop for Mac ###) should be all the outside information that's needed. The Docker edition/version is important because when running something other than the Docker daemon on Linux has networking implications.

I'll add it to my TODO list to come up with an issues template for all our Docker-ized game servers.

> Also, do you mind if I open issues for things like that convar error above?

Absolutely not -- please open up issues directly on the repo so we can discuss, confirm, and address your findings together!

**Pull request merged**
